// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlIJrKNbAOjHDDRNU5GQhcNb3OBzvAKmg',
    appId: '1:812259237256:web:f81aee667ef77c41f4ee3d',
    messagingSenderId: '812259237256',
    projectId: 'clonmc-a8d4c',
    authDomain: 'clonmc-a8d4c.firebaseapp.com',
    storageBucket: 'clonmc-a8d4c.appspot.com',
    measurementId: 'G-8N8SPG86KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNApFsqHpTH70G63-kUGJ8dsJ4jHSIZzM',
    appId: '1:812259237256:android:33370940f9d78cdef4ee3d',
    messagingSenderId: '812259237256',
    projectId: 'clonmc-a8d4c',
    storageBucket: 'clonmc-a8d4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKB4oj0gfWBgikQ2fVJARXQCUWu9XRLrU',
    appId: '1:812259237256:ios:5295b06db1b76c53f4ee3d',
    messagingSenderId: '812259237256',
    projectId: 'clonmc-a8d4c',
    storageBucket: 'clonmc-a8d4c.appspot.com',
    iosClientId: '812259237256-ct71vpivq93iaigj0dll1ids39do75kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKB4oj0gfWBgikQ2fVJARXQCUWu9XRLrU',
    appId: '1:812259237256:ios:8a7f436ed84e9591f4ee3d',
    messagingSenderId: '812259237256',
    projectId: 'clonmc-a8d4c',
    storageBucket: 'clonmc-a8d4c.appspot.com',
    iosClientId: '812259237256-3f4kadtts48r3fpatcfui84e2c04krio.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
